let log = console.log;

const buttons = document.querySelectorAll('button');

const show = document.querySelector('.showMatch');
const p = document.createElement('p');
let scorep = 0;
let scorec = 0;

buttons.forEach((button) => {
    button.addEventListener('click', () => {
        if (scorep < 5 && scorec < 5) {
            let option;
            option = (button.className == 'btnRock') ? 'rock' : (button.className == 'btnPaper') ? 'paper' : 'scissor';
            let c_option = getComputerChoice();
            p.textContent = 'computer: ' + c_option + ', you: ' + option + ", " + playRound(option, c_option);
          //log(scorep+" "+scorec);
        }if(scorep == 5 || scorec == 5) {
            let score = (scorep == 5) ? 'The winner is YOU!' : 'The winner is the COMPUTER!';
            alert(score);
        }
    });
});


show.appendChild(p);

function getComputerChoice() { //GETS AN OPTION GENERATED BY MATH.RANDOM(COMPUTER)
    const aleatorio = Math.floor(Math.random() * 10);
    if (aleatorio >= 0 && aleatorio <= 3) {
        return 'scissor';
    }
    else if (aleatorio > 3 && aleatorio <= 6) {
        return 'rock';
    }
    else if (aleatorio > 6 && aleatorio <= 9) {
        return 'paper';
    }
}

///['rock'>'scissor']
///['paper'>'rock']          
///['scissor'>'paper'] 

function playRound(playerSelection, computerSelection) { //MAKE THE PLAYROUND WITH THE PLAYER OPTION AND THE COMPUTER OPTION
    //console.log('computer: '+computerSelection+ ', You: ', playerSelection);
    const p = playerSelection;
    const c = computerSelection;
    const rock = 'rock'; const paper = 'paper'; const scissor = 'scissor';
    if (playerSelection === computerSelection) {
        return 'Tie!';
    } else {
        if (p === rock) {
            if (c === scissor) {
                scorep++;
                return 'you won! rock beats scissor!';
            }
            if (c === paper) {
                scorec++;
                return 'you lose! paper beats rock!';
            }
        }
        if (p === paper) {
            if (c === rock) {
                scorep++;
                return 'You won! paper beats rock';
            }
            if (c === scissor) {
                scorec++;
                return 'You lose! scissor beats paper';
            }
        }
        if (p === scissor) {
            if (c === paper) {
                scorep++;
                return 'You won! scissor beats paper!';
            }
            if (c === rock) {
                scorec++;
                return 'You lose! rock beats scissor!';
            }
        }
    }
}
